module.exports = {
  // Since `gatsby-plugin-typescript` is automatically included in Gatsby you
  // don't need to define it here (just if you need to change the options)
  siteMetadata: {
    title: 'Gatsby Default Starter',
    menuLinks:[
      {
         name: 'home',
         link: '/'
      },
      {
         name: 'blog',
         link: '/blog'
      },
      {
        name: 'photos',
        link: '/photography'
      }
    ]
  },
  pathPrefix: "/Personal-Site",
  plugins: [
    {
      resolve: `gatsby-plugin-sass`,
      options: {
        postCssPlugins: [
          require("tailwindcss"),
        ],
      },
    },
    // This is incredibly slow on each save
    // TODO: Needs updating to the better maintained version mentioned in it's repo (when it's fixed)
    // https://github.com/cometkim/gatsby-plugin-typegen
    // {
    //   resolve: `gatsby-plugin-graphql-codegen`,
    //   options: {
    //     fileName: `./src/__autogenerated__/gatsby-graphql.ts`,
    //   }
    // },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images/misc`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `projectImages`,
        path: `${__dirname}/src/images/project_images`,
      },
    },
    `gatsby-transformer-sharp`, 
    `gatsby-plugin-sharp`
  ],
};
