import ProjectInfo from "@/static_data/ProjectsInfo";
import { ProjectImagesQuery } from "@/__autogenerated__/gatsby-graphql";
import { IGatsbyImageData } from "gatsby-plugin-image";

type ProjectInfoWithImage = {
  imageSrc: IGatsbyImageData;
  info: ProjectInfo;
};
const useProjectInfoBuilder = (
  images: ProjectImagesQuery,
): ProjectInfoWithImage[] => {
  const projectsInfo = ProjectInfo();

  return projectsInfo.map<ProjectInfoWithImage>((project, indx) => {
    return {
      imageSrc: images.allFile.edges[indx].node.childImageSharp
        .gatsbyImageData as IGatsbyImageData,
      info: project,
    };
  });
};

export default useProjectInfoBuilder;
