# This is a basic workflow to help you get started with Actions

name: Gatsby Publish to Github Pages

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v15
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: yarn install
        run: yarn install
      - name: tsc
        uses: icrawl/action-tsc@v1
  build:
    runs-on: ubuntu-latest
    needs: tsc
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: gh-pages
          gatsby-args: --prefix-paths
